### ISSUE TITLE
Windows 11 test 

### ISSUE THREAD

**Issue by Ryan-py** [ShawnHymel/vscode-env-zephyr#2]
Hello @ShawnHymel, here’s what I used:  
1. Windows 11 OS  
2. Xiao ESP32-S3 (I modified the device tree to match it)  

 I encountered a problem with:  
> `docker run --rm -it -v %cd%\workspace\:/workspace -w /workspace --add-host=host.docker.internal:host-gateway env-zephyr-espressif bash`  

I consistently received this error: `exec /entrypoint.sh: no such file or directory`  

It appears the bash file isn’t executing. However, after overriding `--entrypoint /bin/bash` and running the bash commands myself, everything else worked perfectly.  

![GIFMaker_me 1](https://github.com/user-attachments/assets/a9edc687-5739-455c-9396-bf97637be251)

**Comment by ShawnHymel** [comment]
Hi @Ryan-py,

Thank you for trying out the Docker image, and I definitely appreciate the issue!

To verify, can you run the image and see if /entrypoint.sh exists? It should have been copied in with https://github.com/ShawnHymel/vscode-env-zephyr/blob/b9cbfdff7c3a7fbef9d9e798d49d5f1d498c55aa/Dockerfile.espressif#L124

Best,

Shawn

**Comment by Ryan-py** [comment]
Hello @ShawnHymel , 
I  actually checked for the file and its in the image.

**Comment by ShawnHymel** [comment]
Hmmm...this one has me stumped, considering you see the /entrypoint.sh file in the image when you fire up a container. Any luck so far?

**Comment by ShawnHymel** [comment]
I got rid of /entrypoint.sh in favor of adding the source calls to /root/.bashrc. I'm also using code-server instead of manually editing files now. If you try it again, let me know!
