### ISSUE TITLE
Windows Instructions update

### ISSUE THREAD

**Issue by sethkaz** [ShawnHymel/vscode-env-zephyr#4]
I'm running Windows 10 and found I need to make the following mods to get it to work:

1. For running the VS Code Server, I needed to make the following mods:
   1. I used `-v ${pwd}\workspace:/workspace` within PowerShell for it to register the right directory.
   2. I had to swap out the port, as I couldn't disable what was grabbing 8080 on my machine.  I used this flag instead `-p 8090:8080` and went to localhost:8090, and it worked. 
1. From the docs, it's not obvious, but the flashing step should happen outside of the VS Code Server, and back in the host machine terminal. Also, it's not clear that the working directory is back in the root of the repo.  (The latter is somewhat obvious once you change back to the host machine terminal, as we launched the docker image from the repo-root, so we should already be there.)

(P.S. Thanks for putting this together Shawn!)

**Comment by ShawnHymel** [comment]
Thanks for letting me know! I've updated the README to use PowerShell (since that seems to be the default now) and made a note about using the host computer for flashing.
